#!/usr/bin/env bash

#script that pings IP address passed as an argument
#it displays usage: 5-is_the_host_on_the_network
#it will ping the IP 5 times

if ["$#" -lt "1"]
then
	echo "Usage: 5-is_the_host_on_the_network{IP_ADDRESS}"
else
	ping "$1" -c 5
fi
