#!/usr/bin/env bash
#script displays messages when receiving signals

echo $$ > /var/run/myscript.pid
trap 'echo "I hate the kill command"; rm -rf /var/run/myscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -rf /var/run/myscript.pid; exit' SIGQUIT
while:
do
	echo "TO infinity and beyond"
	sleep 2
done
